### ISSUE TITLE
Generated class should not be checked-in in git

### ISSUE THREAD

**Issue by jarl-dk** [Grails-Plugin-Consortium/grails-cxf-client-demo#3]
the files in
```
src/main/java/cxf/client
```

See https://github.com/Grails-Plugin-Consortium/grails-cxf-client/issues/67

**Comment by ctoestreich** [comment]
I finally got some time to look at this and there is a bit of a chicken-egg problem, but that can't really be avoided in this demo project as it uses BOTH cxf and cxf client.  I will make a branch here that doesn't have any exposed services to call.  At one point I think I had moved the cxf services to a jar and then the client could generate sources on it's own.  I think that got lost a while back in the 2->3 conversion.

**Comment by ctoestreich** [comment]
responded and closed via [Grails-Plugin-Consortium/grails-cxf-client#67](https://github.com/Grails-Plugin-Consortium/grails-cxf-client/issues/67)
